# QCArchive Demo

In [1]:
import qcportal as ptl
client = ptl.FractalClient()

In [24]:
import numpy as np

In [2]:
client

FractalClient(server_name='The MolSSI QCArchive Server', address='https://api.qcarchive.molssi.org:443/', username='None')

In [3]:
butane = client.query_molecules(id=['61139','70659'])

In [7]:
butane

[<Molecule(name='C4H10' formula='C4H10' hash='3bbc6db')>,
 <Molecule(name='C4H10' formula='C4H10' hash='bb665a3')>]

In [4]:
butane[0].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [6]:
butane[1].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [9]:
dir(butane[0])

['Config',
 '__abstractmethods__',
 '__annotations__',
 '__class__',
 '__config__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__fields__',
 '__fields_set__',
 '__format__',
 '__ge__',
 '__get_validators__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__validators__',
 '__values__',
 '__weakref__',
 '_abc_impl',
 '_calculate_keys',
 '_custom_root_type',
 '_decompose_class',
 '_get_key_factory',
 '_get_value',
 '_inertial_tensor',
 '_iter',
 '_json_encoder',
 '_orient_molecule_internal',
 '_repr_html_',
 '_schema_cache',
 'align',
 'atom_labels',
 'atomic_numbers',
 'comment',
 'compare',
 'connectivity',
 'construct',
 'copy',
 'dict',
 'extras',
 'fields',
 'fix_com',
 'fix_orientat

In [13]:
butane[0].atomic_numbers

[6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [29]:
butane_geometries = [butane[0].geometry.copy(), butane[1].geometry.copy()]

In [15]:
butane[0].symbols

['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']

In [30]:
butane_geometries

[array([[ 0.60309252, -2.0666753 , -2.95631542],
        [-0.54975128,  2.07257294,  2.96267825],
        [ 0.17543623, -1.41965569, -0.1899598 ],
        [-0.17535536,  1.41986451,  0.18990506],
        [-0.98243014, -1.42706018, -4.12126516],
        [ 2.32107194, -1.14665691, -3.64966894],
        [ 0.81868895, -4.10783439, -3.21556669],
        [ 1.07104045,  1.43010767,  4.07529687],
        [-2.24715359,  1.16149057,  3.71618302],
        [-0.73832413,  4.11600143,  3.22440978],
        [ 1.79270627, -2.08396319,  0.92115557],
        [-1.4961426 , -2.4339562 ,  0.49460988],
        [-1.81551707,  2.07754179, -0.89074739],
        [ 1.48034939,  2.43606453, -0.52991943]]),
 array([[-0.69390481, -2.34149626, -1.69148799],
        [-1.52276705,  2.12200941,  1.41576994],
        [ 1.67240752, -1.04497304, -0.64735584],
        [ 1.23080507,  1.33319296,  1.00805961],
        [-1.91853592, -3.01948807, -0.12936141],
        [-1.76605429, -1.03734012, -2.93620015],
        [-0.123106

In [20]:
def calculate_distance(rA, rB):
    """Calculate the distance between points A and B"""
    dist_vec = (rA - rB)
    distance = np.linalg.norm(dist_vec)
    return distance

In [21]:
def build_bond_list(coords,max_bond=1.55,min_bond=0): # qc archive geomitries are in bohr not angstrom 
    num_atoms = len(coords)
    bonds = {}
    for atom1 in range(num_atoms):
        for atom2 in range(atom1,num_atoms):
            distance = calculate_distance(coords[atom1],coords[atom2])
            if distance > min_bond and distance < max_bond:
                bonds[(atom1,atom2)] = distance
    return bonds

In [31]:
bond_list = build_bond_list(butane_geometries[0])

In [32]:
bond_list

{}

In [27]:
import qcelemental

In [28]:
angstrom_to_bohr = qcelemental.constants.conversion_factor('angstrom','bohr') # this pulls the converion factor from
                                                                              # angtroms to bohr
print(angstrom_to_bohr)

1.8897261254578281


In [33]:
atom1 = butane_geometries[0][0]
atom2 = butane_geometries[0][1]
print(atom1)
print(atom2)

[ 0.60309252 -2.0666753  -2.95631542]
[-0.54975128  2.07257294  2.96267825]


In [34]:
measured_distance = calculate_distance(atom1,atom2)

In [35]:
print(measured_distance)

7.314158248564329


In [36]:
butane[0].measure([0,1]) # if our cistance function prints the same as this function the distanc function is correct

7.31415824856433

In [38]:
# use calculate distnace to measure the distance between atom3 and atom10
distance = calculate_distance(butane_geometries[1][2],butane_geometries[1][9])

In [39]:
print(distance)

6.71634950813261


In [41]:
print(butane[1].measure([2,9]))

6.71634950813261


In [42]:
bond_list = build_bond_list(butane_geometries[0],max_bond = 2.93)

In [43]:
print(bond_list)

{(0, 2): 2.873020656801253, (0, 4): 2.068839651551603, (0, 5): 2.068484041315794, (0, 6): 2.068821759435787, (1, 3): 2.873059651780396, (1, 7): 2.068247482474781, (1, 8): 2.0685780442929644, (1, 9): 2.0687346633381822, (2, 3): 2.8862132661474598, (2, 10): 2.0715801221019885, (2, 11): 2.0716218178677623, (3, 12): 2.0713472807014583, (3, 13): 2.071754810836534}


In [44]:
bond_list

{(0, 2): 2.873020656801253,
 (0, 4): 2.068839651551603,
 (0, 5): 2.068484041315794,
 (0, 6): 2.068821759435787,
 (1, 3): 2.873059651780396,
 (1, 7): 2.068247482474781,
 (1, 8): 2.0685780442929644,
 (1, 9): 2.0687346633381822,
 (2, 3): 2.8862132661474598,
 (2, 10): 2.0715801221019885,
 (2, 11): 2.0716218178677623,
 (3, 12): 2.0713472807014583,
 (3, 13): 2.071754810836534}

In [46]:
butane[0].connectivity # atom1 atom2 bond order

[(0, 2, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (0, 6, 1.0),
 (1, 3, 1.0),
 (1, 7, 1.0),
 (1, 8, 1.0),
 (1, 9, 1.0),
 (2, 3, 1.0),
 (2, 10, 1.0),
 (2, 11, 1.0),
 (3, 12, 1.0),
 (3, 13, 1.0)]

In [50]:
# let's see what the anwser is for a molecule we can't pull the connectivety for
# use qcportla to acsses a geometry optimization calculation
# us query_proceures
# id = 2658710

optimization = client.query_procedures(id='2658710')

In [48]:
optimization

[<OptimizationRecord(id='2658710' status='COMPLETE')>]

In [54]:
opt = optimization[0]

In [55]:
initial = opt.get_initial_molecule()

In [56]:
initial.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [59]:
final = opt.get_final_molecule()
final.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [68]:
initial_coords = initial.geometry.copy()
final_coords = final.geometry.copy()

In [70]:
bond_list_initial = build_bond_list(initial_coords,max_bond=2.93)

In [73]:
bond_list_final = build_bond_list(final_coords,max_bond=2.93)


In [78]:
for i in bond_list_initial.keys():
    print(F'bond {i} initial = {bond_list_initial[i]} final = {bond_list_final[i]} change = {bond_list_initial[i]-bond_list_final[i]}')

bond (0, 1) initial = 2.6853008199999997 final = 2.5640429800175255 change = 0.12125783998247419
bond (0, 5) initial = 2.685300947458371 final = 2.721830285918179 change = -0.03652933845980799
bond (0, 54) initial = 2.0494834766860643 final = 2.050790758811911 change = -0.0013072821258468537
bond (1, 6) initial = 2.6853009524690883 final = 2.7218295881283754 change = -0.0365286356592871
bond (1, 55) initial = 2.0494834766860643 final = 2.0507899790642936 change = -0.0013065023782292684
bond (2, 3) initial = 2.6853008199999997 final = 2.5640476200137154 change = 0.12125319998628425
bond (2, 9) initial = 2.685300947458371 final = 2.7218316161338745 change = -0.036530668675503364
bond (2, 56) initial = 2.0494834766860643 final = 2.0507897182972523 change = -0.0013062416111879749
bond (3, 10) initial = 2.6853009524690883 final = 2.7218322358238627 change = -0.0365312833547744
bond (3, 57) initial = 2.0494834766860643 final = 2.0507903323327072 change = -0.0013068556466429015
bond (4, 5) in